-- 暂时禁用 RLS
ALTER TABLE public.activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.persons DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_leaders DISABLE ROW LEVEL SECURITY;